# This file describes the plugin
name: demo_1_minimal
author: Ajenti project
email: e@ajenti.org
url: http://ajenti.org
version: '0.1'
title: 'Demo 1 (minimal)'
icon: question
# add a dependency on the 'core' plugin (not really required in the minimal example)
dependencies:
    - !!python/object:aj.plugins.PluginDependency {
        plugin_name: core
    }
resources: []
