name: demo_3_bower
author: Ajenti project
email: e@ajenti.org
url: http://ajenti.org
version: '0.1'
title: 'Demo 3 (Bower)'
icon: question
dependencies:
    - !PluginDependency {
        plugin_name: core
    }
resources:
    # it's important to include the required Bower resources here
    - 'resources/vendor/Chart.js/Chart.min.js'
    - 'resources/vendor/angular-chart.js/dist/angular-chart.min.js'
    - 'resources/vendor/angular-chart.js/dist/angular-chart.css'
    - 'resources/js/module.coffee'
    - 'resources/js/routing.coffee'
    - 'resources/js/controllers/index.controller.coffee'
    - 'resources/partial/index.html'
    - 'ng:ajenti.demo3'
