name: demo_5_widget
author: Ajenti project
email: e@ajenti.org
url: http://ajenti.org
version: '0.1'
title: 'Demo 5 (Widget)'
icon: question
dependencies:
    - !PluginDependency {
        plugin_name: core
    }
    - !PluginDependency {
        plugin_name: dashboard
    }
resources:
    - 'resources/js/module.coffee'
    - 'resources/js/controllers/widget.controller.coffee'
    - 'resources/partial/widget.html'
    - 'resources/partial/widget.config.html'
    - 'ng:ajenti.demo5'
