name: demo_4_http
author: Ajenti project
email: e@ajenti.org
url: http://ajenti.org
version: '0.1'
title: 'Demo 4 (HTTP)'
icon: question
dependencies:
    - !PluginDependency {
        plugin_name: core
    }
resources:
    - 'resources/js/module.coffee'
    - 'resources/js/routing.coffee'
    - 'resources/js/controllers/index.controller.coffee'
    - 'resources/partial/index.html'
    - 'ng:ajenti.demo4'
